EMERGENCY_STOP_DISTANCE = 9
STOP_DISTANCE = 18
BRAKE_DISTANCE = 26
SLOW_DISTANCE = 36

NORMAL_SPEED = 22
SLOW_SPEED = 14
LOW_CONFIDENCE_SPEED = 12
CORNER_SPEED = 14
SEARCH_SPEED = 10
AVOID_SPEED = 16

AVOID_LEFT_ANGLE = -28
AVOID_RIGHT_ANGLE = 30

AVOID_TURN_TIME = 0.35
RETURN_TURN_TIME = 0.30

ULTRASONIC_WINDOW = 5
OBSTACLE_CONFIRM_FRAMES = 2
CLEAR_CONFIRM_FRAMES = 3

# Speed settings
REVERSE_SPEED = -20

# Steering
STEERING_LIMIT = 45
MAX_STEERING_STEP = 5.0

# PID tuning
KP = 0.52
KI = 0.0
KD = 0.11
PID_INTEGRAL_LIMIT = 35.0
DERIVATIVE_SMOOTHING = 0.30

# Lane control weights
OFFSET_WEIGHT = 1.0
ANGLE_WEIGHT = 1.55

# Camera lane detection
ROI_TOP_RATIO = 0.42

# Relative scanline positions inside ROI
SCANLINES = [0.10, 0.28, 0.46, 0.64, 0.82]

WHITE_THRESHOLD = 165
WHITE_HLS_LIGHTNESS_MIN = 165
WHITE_HLS_SATURATION_MAX = 95
WHITE_HSV_VALUE_MIN = 175
WHITE_HSV_SATURATION_MAX = 60
MASK_MORPH_KERNEL = 3
MIN_WHITE_PIXELS = 5

MIN_LANE_WIDTH = 70
MAX_LANE_WIDTH = 520

# If only one border is visible
EXPECTED_LANE_WIDTH = 280

# Smoothing
STEERING_SMOOTHING = 0.28
ERROR_SMOOTHING = 0.32
LANE_MIN_CONFIDENCE = 0.55
LANE_LOSS_GRACE_TIME = 0.65

# Corner handling
CORNER_ERROR_THRESHOLD = 12
CORNER_ANGLE_THRESHOLD_DEG = 8

# Debug
DEBUG_MODE = True

# Street sign handling
SIGN_DETECTION_ENABLED = True
SIGN_ACTION_DELAY = 0.35
SIGN_CONFIRM_FRAMES = 2
SIGN_COOLDOWN = 3.0
SIGN_PENDING_TIMEOUT = 0.35
SIGN_TURN_SPEED = 14
SIGN_LEFT_ANGLE = -35
SIGN_RIGHT_ANGLE = 35
SIGN_TURN_TIME = 0.8
SIGN_STOP_HOLD_TIME = 2.0
