EMERGENCY_STOP_DISTANCE = 10
STOP_DISTANCE = 20
BRAKE_DISTANCE = 28
SLOW_DISTANCE = 40

NORMAL_SPEED = 30
SLOW_SPEED = 18
LOW_CONFIDENCE_SPEED = 16
CORNER_SPEED = 20
SEARCH_SPEED = 15
AVOID_SPEED = 22

AVOID_LEFT_ANGLE = -28
AVOID_RIGHT_ANGLE = 30

AVOID_TURN_TIME = 0.45
RETURN_TURN_TIME = 0.40

ULTRASONIC_WINDOW = 5
OBSTACLE_CONFIRM_FRAMES = 2
CLEAR_CONFIRM_FRAMES = 3

# Speed settings
REVERSE_SPEED = -20

# Steering
STEERING_LIMIT = 45
MAX_STEERING_STEP = 6.0

# PID tuning
KP = 0.45
KI = 0.0
KD = 0.08
PID_INTEGRAL_LIMIT = 35.0
DERIVATIVE_SMOOTHING = 0.25

# Lane control weights
OFFSET_WEIGHT = 1.0
ANGLE_WEIGHT = 1.8

# Camera lane detection
ROI_TOP_RATIO = 0.55

# Relative scanline positions inside ROI
SCANLINES = [0.20, 0.40, 0.60, 0.80]

WHITE_THRESHOLD = 180
WHITE_HLS_LIGHTNESS_MIN = 170
WHITE_HLS_SATURATION_MAX = 120
WHITE_HSV_VALUE_MIN = 180
WHITE_HSV_SATURATION_MAX = 80
MASK_MORPH_KERNEL = 5
MIN_WHITE_PIXELS = 5

MIN_LANE_WIDTH = 40
MAX_LANE_WIDTH = 500

# If only one border is visible
EXPECTED_LANE_WIDTH = 220

# Smoothing
STEERING_SMOOTHING = 0.35
ERROR_SMOOTHING = 0.25
LANE_MIN_CONFIDENCE = 0.45

# Corner handling
CORNER_ERROR_THRESHOLD = 18
CORNER_ANGLE_THRESHOLD_DEG = 10

# Debug
DEBUG_MODE = True
